services:
  vite-react-app:
    image: takecare-solution-backoffice:latest        
    build:
      context: .                           
      dockerfile: Dockerfile               
    ports:
      - "5173:80"                           
    env_file:
      - .env.production
    extra_hosts:
      - "test-apitakecaresolution.attg.cc:43.249.65.230"              
